name: 'Get and Cache Dependencies'
description: 'Get the dependencies (via npm) and cache them'

inputs:
  caching:
    description: 'Whether to cache dependencies or not'
    required: false
    default: 'true'
  message:
    description: 'Hanya message biasa'
    required: true
outputs:
  used-cache:
    description: 'Whether the cache was used'
    value: ${{ steps.install.outputs.cache }}
  output-message:
    description: 'Only output message'
    value: ${{ steps.output-message.outputs.message }}
runs:
  using: 'composite'
  steps:
    - name: Only output inputted message
      id: output-message
      run: echo "message='${{ inputs.message }}'" >> $GITHUB_OUTPUT
      shell: bash
    - name: Output the branch
      id: output-branch
      run: echo "${{ GITHUB_REF }}"
      shell: bash