name: Deployment
on:
  push:
    branches:
      - master
      - 'daily/**'
  workflow_dispatch:
    braches:
      - master
      - 'daily/**'
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Load & cache dependencies
        id: cache-deps
        uses: ./.github/actions/cache-deps
        with:
          message: 'Gilbert Subay'
      - name: Output Information
        run: echo "What is the message? ${{ steps.cache-deps.outputs.output-message }}"
      - name: Lint code
        run: npm run lint